mysite/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:service_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:service_id>/', views.cart_remove, name='cart_remove'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from rest_framework import routers
from django.conf import settings
from django.conf.urls.static import static

from store.views import ServiceViewSet, UserViewSet, mainpage_view

router = routers.DefaultRouter()

router.register(r'users', UserViewSet)
router.register(r'services', ServiceViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    re_path('', include('social_django.urls', namespace='social')),
    path('store/', include('store.urls', namespace='store')),
    path('accounts/', include("django.contrib.auth.urls")),
    path('', mainpage_view, name='mainpage')
]


urlpatterns += router.urls

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mysite/store/urls.py
from django.urls import path

from store.views import profile_view, RegisterView, service_list, service_detail

app_name = 'store'

urlpatterns = [
    path('', service_list, name='service_list'),
    path('<slug:category_slug>/', service_list, name='service_list_by_category'),
    path('<int:id>/<slug:slug>/', service_detail, name='service_detail'),
    path('profile', profile_view, name='profile'),
    path('register', RegisterView.as_view(), name="register"),

]

mysite/cart/forms.py
from django import forms

SERVICE_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddServiceForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=SERVICE_QUANTITY_CHOICES, coerce=int)
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

mysite/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from store.models import Service
from .cart import Cart
from .forms import CartAddServiceForm


@require_POST
def cart_add(request, service_id):
    cart = Cart(request)
    service = get_object_or_404(Service, id=service_id)
    form = CartAddServiceForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(service=service, quantity=cd['quantity'], override_quantity=cd['override'])
    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, service_id):
    cart = Cart(request)
    service = get_object_or_404(Service, id=service_id)
    cart.remove(service)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddServiceForm(initial={
            'quantity': item['quantity'],
            'override': True})
    return render(request, 'cart/detail.html', {'cart': cart})

mysite/cart/templates/cart/detail.html
{% extends "store/base.html" %}
{% load static %}
{% block title %}
Your shopping cart
{% endblock %}
{% block content %}
<h1>Ваша корзина</h1>
<table class="cart">
    <thead>
    <tr>
        <th>Изображение</th>
        <th>Услуга</th>
        <th>Количество</th>
        <th>Удалить</th>
        <th>Цена за единицу</th>
        <th>Общая цена</th>
    </tr>
    </thead>
    <tbody>
    {% for item in cart %}
    {% with service=item.service %}
    <tr>
        <td>
            <a href="{{ service.get_absolute_url }}">
                <img src="{% if service.image %}{{ service.image.url }} {% else %} {% static "img/no_image.png" %}{% endif %}">
            </a>
        </td>
        <td>{{ service.title }}</td>
        <td>
            <form action="{% url "cart:cart_add" service.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.override }}
                <input type="submit" value="Обновить">
                {% csrf_token %}
            </form>
        </td>
        <td>
            <form action="{% url "cart:cart_remove" service.id %}"
            method="post">
            <input type="submit" value="Удалить">
            {% csrf_token %}
            </form>
        </td>
        <td class="num">{{ item.price }}р</td>
        <td class="num">{{ item.total_price }}р</td>
    </tr>
    {% endwith %}
    {% endfor %}
    <tr class="total">
        <td>Total</td>
        <td colspan="4"></td>
        <td class="num">{{ cart.get_total_price }}р</td>
    </tr>
    </tbody>
</table>
<p class="text-right">
    <a href="{% url "store:service_list" %}" class="button
    light">Продолжить покупки</a>
    <a href="#" class="button">Оплатить</a>
</p>
{% endblock %}