mysite/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:service_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:service_id>/', views.cart_remove, name='cart_remove'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from rest_framework import routers
from django.conf import settings
from django.conf.urls.static import static

from store.views import ServiceViewSet, UserViewSet, mainpage_view

router = routers.DefaultRouter()

router.register(r'users', UserViewSet)
router.register(r'services', ServiceViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    re_path('', include('social_django.urls', namespace='social')),
    path('store/', include('store.urls', namespace='store')),
    path('accounts/', include("django.contrib.auth.urls")),
    path('', mainpage_view, name='mainpage')
]


urlpatterns += router.urls

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mysite/store/urls.py
from django.urls import path

from store.views import profile_view, RegisterView, service_list, service_detail

app_name = 'store'

urlpatterns = [
    path('', service_list, name='service_list'),
    path('<slug:category_slug>/', service_list, name='service_list_by_category'),
    path('<int:id>/<slug:slug>/', service_detail, name='service_detail'),
    path('profile', profile_view, name='profile'),
    path('register', RegisterView.as_view(), name="register"),

]

mysite/store/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Category(models.Model):
    '''Модель категории товаров'''
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ['name']
        indexes = [models.Index(fields=['name']), ]
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('store:service_list_by_category', args=[self.slug])


class Service(models.Model):
    '''Модель услуг/товаров'''
    category = models.ForeignKey(Category, related_name='services', on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=200, null=True)
    image = models.ImageField(upload_to='services/%Y/%m/%d', blank=True)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    description = models.TextField(null=True)
    viewers = models.ManyToManyField(User, through='UserServiceRelation', related_name='service')
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='my_service')

    class Meta:
        ordering = ['title']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['title']),
            models.Index(fields=['-created']),
        ]

    def __str__(self):
        return f'Id {self.id}: {self.title}'

    def get_absolute_url(self):
        return reverse('store:service_detail', args=[self.id, self.slug])


class UserServiceRelation(models.Model):
    '''Модель оценки пользователем услуги'''
    RATE_CHOICES = (
        (1, 'Terribly'),
        (2, 'Bad'),
        (3, 'Fine'),
        (4, 'Good'),
        (5, 'Awsome')
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    service = models.ForeignKey(Service, on_delete=models.CASCADE, null=True)
    like = models.BooleanField(default=False)
    in_bookmark = models.BooleanField(default=False)
    rate = models.PositiveIntegerField(choices=RATE_CHOICES, null=True)

    def __str__(self):
        return f'{self.user.username} {self.service}, rate: {self.rate}'

mysite/store/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import FormView
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import SearchFilter, OrderingFilter
from rest_framework.mixins import UpdateModelMixin
from rest_framework.viewsets import ModelViewSet, GenericViewSet
from rest_framework import permissions
from django.contrib.auth.models import User

from cart.forms import CartAddServiceForm
from store.models import Service, UserServiceRelation, Category
from store.permissions import IsOwnerOrStaffOrReadOnly
from store.serializers import ServiceSerializer, UserSerializer, UserServiceRelationSerializer

'''------------------api------------------'''


class UserViewSet(ModelViewSet):
    '''Конечная точка API, которая позволяет просматривать или редактировать пользователей.'''
    queryset = User.objects.all()
    serializer_class = UserSerializer
    permission_classes = [permissions.IsAuthenticated]


class ServiceViewSet(ModelViewSet):
    '''Конечная точка API, которая позволяет просматривать или редактировать услуги'''
    queryset = Service.objects.all()
    serializer_class = ServiceSerializer
    permission_classes = [IsOwnerOrStaffOrReadOnly]
    filter_backends = [DjangoFilterBackend, SearchFilter, OrderingFilter]
    filterset_fields = ['price']
    search_fields = ['title', 'price']
    ordering_fields = ['title', 'price']

    def perform_create(self, serializer):
        serializer.validated_data['owner'] = self.request.user
        serializer.save()


class UserServiceRelationView(UpdateModelMixin, GenericViewSet):
    '''API для просмотра оценок услуг'''
    queryset = UserServiceRelation.objects.all()
    permission_classes = [permissions.IsAuthenticated]
    serializer_class = UserServiceRelationSerializer
    lookup_field = 'service'

    def get_object(self):
        obj, _ = UserServiceRelation.objects.get_or_create(user=self.request.user, service_id=self.kwargs['service'])

        return obj


@login_required
def profile_view(request):
    context = {'css': 'css/style.css'}
    return render(request, 'store/profile.html', context)


class RegisterView(FormView):
    form_class = UserCreationForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy('store:profile')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


def mainpage_view(request):
    context = {'css': 'css/mainpage.css'}
    return render(request, 'store/mainpage.html', context)


def service_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    services = Service.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        services = services.filter(category=category)
    return render(request, 'store/service/list.html', {
        'category': category,
        'categories': categories,
        'services': services
    })


def service_detail(request, id, slug):
    service = get_object_or_404(Service, id=id, slug=slug, available=True)

    cart_service_form = CartAddServiceForm()
    return render(request, 'store/service/detail.html', {'service': service, 'cart_service_form': cart_service_form})

mysite/store/templates/store/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}My store{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
<div id="header">
    <a href="/store/" class="logo">My store</a>
</div>
<div id="subheader">
    <div class="cart">
        {% with total_items=cart|length %}
            {% if total_items > 0 %}
                Корзина:
                <a href="{% url 'cart:cart_detail' %}">
                    {{ cart.get_total_price }}р
                </a>
            {% else %}
                Ваша корзина пуста.
            {% endif %}
           {% endwith %}
        <div class="hidden md:flex items-center space-x-1"><a href="{% url 'store:profile' %}"
                                                              class="py-5 px-3">Login</a>
           <a href="/store/register" class="py-2 px-3 bg-yellow-400 text-white hover:bg-yellow-300 text-sm hover:text-yellow-800 rounded transition duration-300">Signup</a>
        </div>
    </div>
    <div class="hidden md:flex items-center space-x-1"><a href="{% url 'mainpage' %}"
                                                          class="py-5 px-3 text-gray-700 hover:text-gray-900">На главную сайта</a>
    </div>
</div>
<div id="content">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

mysite/store/templates/store/mainpage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/mainpage.css' %}">
    <title>Store</title>
    <link rel="stylesheet" href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css"></script>

</head>
<body>
<!-- navbar goes here -->
<header class="bg-gray-100">
    <nav>
        <div class="max-w-6xl mx-auto px-4">
            <div class="flex justify-between">
                <div class="flex space-x-4">
                    <!-- logo -->
                    <div class="hidden md:flex items-center space-x-1"><a href="{% url 'mainpage' %}"
                                                                          class="py-5 px-3 text-gray-700 hover:text-gray-900">Контакты</a>
                    </div>
                    <div class="hidden md:flex items-center space-x-1"><a href="{% url 'store:service_list' %}"
                                                                          class="py-5 px-3 text-gray-700 hover:text-gray-900">Магазин</a>
                    </div>
                </div> <!-- secondary nav -->
                <div class="hidden md:flex items-center space-x-1"><a href="{% url 'store:profile' %}"
                                                                      class="py-5 px-3">Login</a>
                    <a href="{% url 'store:register' %}"
                       class="py-2 px-3 bg-yellow-400 text-white hover:bg-yellow-300 text-sm hover:text-yellow-800 rounded transition duration-300">Signup</a>
                </div> <!-- mobile button goes here -->
                <div class="md:hidden flex items-center">
                    <button class="mobile-menu-button focus:outline-none">
                        <i class='bx bx-menu text-3xl mt-1'></i></button>
                </div>
            </div>
        </div> <!-- mobile menu -->
        <div class="mobile-menu hidden md:hidden"><a href="{% url 'mainpage' %}"
                                                     class="block py-2 px-4 text-sm hover:bg-gray-200">Home</a></div>

    </nav>
</header>
<main>

</main>
</div>
</body>
</html>

mysite/store/templates/store/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
    <title>Profile</title>
</head>
<body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <div class="page-content page-container" id="page-content">
    <div class="padding">
        <div class="row container d-flex justify-content-center">

<div class="col-md-5">
							<div class="card">
								<div class="card-body text-center">
									<div>
										<img src="https://img.icons8.com/bubbles/100/000000/administrator-male.png" class="img-lg rounded-circle mb-4" alt="profile image">
										<h4>{{ user.username }}</h4>
										<p class="text-muted mb-0">{{ user.email }}</p>
									</div>
									<button class="btn btn-info btn-sm mt-3 mb-4" onclick="location.href='{% url 'logout' %}?next=/store/profile'">Logout</button>

										</div>
									</div>
								</div>
							</div>
						</div>
						</div>
							</div>
						</div>
</div>
</body>
</html>